os:
  - linux
dist: focal

language: go
go:
  - 1.x
  - 1.14.x

services:
  - docker

stages:
  - test
  - name: release
    if: branch = master AND type != pull_request
  
jobs:
  include:
    - stage: release
      install:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      script: ./.travis/
        - docker build -t gql-server .
        - |
          if [-z $TRAVIS_TAG]
          then
            docker tag gql-server $DOCKER_NAMESPACE/gql-server:master
            docker push $DOCKER_NAMESPACE/gql-server:master
          else
            docker tag gql-server $DOCKER_NAMESPACE/gql-server:latest
            docker tag gql-server $DOCKER_NAMESPACE/gql-server:$TRAVIS_TAG
            docker push $DOCKER_NAMESPACE/gql-server:latest
            docker push $DOCKER_NAMESPACE/gql-server:$TRAVIS_TAG
          fi
        - 
