os:
  - linux
dist: focal

language: go
go:
  - 1.x
  - 1.14.x

services:
  - docker

stages:
  - test
  - name: release
    if: branch = master AND type != pull_request
  
jobs:
  include:
    - stage: release
      before_script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      script:
        - docker build -t $DOCKER_NAMESPACE/gql-server .
        - docker images
        - docker push $DOCKER_NAMESPACE/gql-server
